using System.Text;
using Vein.Compiler.Project;
using Vein.Compiler.Service;
using Vein.Compiler.Tooling;

namespace Vein.Cloud;

/// How many characters each part of the context may take.
///
/// The two numbers are not arbitrary. `AssistantApi.MaxMessage` is 4000 for the whole request, and the
/// question has to fit in what is left — so the defaults leave roughly 1200 characters for whatever
/// gets typed, which is a long question. Both are settable so a test can force the trimming paths
/// without building a large fake project.
public sealed record DigestBudget(int Digest = 1200, int ActiveFile = 1600)
{
    public static DigestBudget Default { get; } = new();
}

/// The project, described compactly enough to send with every question.
public sealed record ProjectContext(
    string Text,
    IReadOnlyList<string> Files,
    bool DigestTrimmed,
    bool ActiveFileTrimmed)
{
    public int Chars => Text.Length;
    public bool IsEmpty => Text.Length == 0;

    public static ProjectContext None { get; } =
        new("", Array.Empty<string>(), false, false);

    /// What the panel puts above the composer, so nobody has to guess what left the machine.
    public string Summary => IsEmpty
        ? "No project context sent"
        : $"Context: {Files.Count} file(s), {Chars} chars" +
          (DigestTrimmed || ActiveFileTrimmed ? " (trimmed)" : "");
}

/// The project as the assistant sees it.
///
/// WHY A DIGEST AND NOT THE FILES. `workbenchChat` takes 4000 characters for the question and
/// everything sent with it. A single real bundle is past that on its own, so "attach the project" is
/// not an option that exists — the only question is what to spend the budget on.
///
/// Names beat bodies. Almost every answer that goes wrong goes wrong because the assistant invented a
/// `$Health` that does not exist or emitted an `@Damaged` with the wrong fields; knowing that
/// `$Health { current: int, max: int }` is declared is what prevents that, and it costs one line. The
/// bodies of your shards are what you are asking ABOUT, so the open file is sent separately and in
/// full where it fits.
///
/// Pure and offline: it reads the disk and returns a string, with no network anywhere. That is what
/// lets a test assert the budget is respected, and what lets the panel show the exact text before it
/// is sent.
public static class ProjectDigest
{
    /// Build the context for one question.
    ///
    /// `activeText` is passed in rather than read from disk because the interesting version of the
    /// open file is the one in the editor, unsaved edits and all — that is the version being asked
    /// about. A `selection` replaces it when there is one, since selecting code before asking is how
    /// people say "this bit".
    public static ProjectContext Build(
        string? projectDir, string? activePath, string? activeText, string? selection = null,
        DigestBudget? budget = null)
    {
        budget ??= DigestBudget.Default;

        var (digest, files, digestTrimmed) = Digest(projectDir, budget.Digest);
        var (active, activeTrimmed) = ActiveFile(activePath, activeText, selection, budget.ActiveFile);

        if (digest.Length == 0 && active.Length == 0) return ProjectContext.None;

        var sb = new StringBuilder();
        sb.AppendLine("--- project context (generated by the Workbench; do not repeat it back) ---");
        if (digest.Length > 0) sb.Append(digest);
        if (active.Length > 0) sb.Append(active);
        sb.AppendLine("--- end of context ---");

        return new ProjectContext(sb.ToString(), files, digestTrimmed, activeTrimmed);
    }

    /// Put the context in front of a question, without ever eating the question.
    ///
    /// IF IT WILL NOT FIT, THE CONTEXT GOES, NOT THE WORDS. A truncated question is answered wrongly
    /// and the person cannot see why; a missing digest merely gets a more generic answer. So the
    /// question is measured first and the context takes what is left, or nothing.
    public static string Compose(ProjectContext context, string question, int max = AssistantApi.MaxMessage)
    {
        question = (question ?? "").Trim();
        if (context.IsEmpty) return question;

        string joined = context.Text + "\n" + question;
        return joined.Length <= max ? joined : question;
    }

    // ---- the project ------------------------------------------------------------------------------

    private static (string Text, IReadOnlyList<string> Files, bool Trimmed) Digest(string? dir, int budget)
    {
        var files = new List<string>();
        if (string.IsNullOrEmpty(dir) || !Directory.Exists(dir) || budget <= 0)
            return ("", files, false);

        var sb = new StringBuilder();
        bool trimmed = false;

        // ProjectPackage already walks a project the way the rest of the system understands one —
        // same extensions, same skipped folders, same ordering. Re-walking it here by hand would be a
        // second definition of "the project" that could drift from the one that gets published.
        ProjectPackage package;
        try { package = ProjectPackage.Create(dir); }
        catch (Exception) { return ("", files, false); }

        var svc = new VeinCompilerService();

        foreach (var file in package.Files)
        {
            if (!file.Path.EndsWith(".vein", StringComparison.OrdinalIgnoreCase)) continue;

            string line = Describe(svc, file);
            if (line.Length == 0) continue;

            if (sb.Length + line.Length > budget) { trimmed = true; break; }

            sb.Append(line);
            files.Add(file.Path);
        }

        if (sb.Length == 0) return ("", files, trimmed);

        var head = new StringBuilder();
        head.AppendLine("Files in this project and what each declares:");
        head.Append(sb);
        if (trimmed) head.AppendLine($"  … and {package.Files.Count - files.Count} more file(s), not listed.");

        return (head.ToString(), files, trimmed);
    }

    /// One line per file: its path, then what another file could reference from it.
    ///
    /// A file that does not parse still gets its line — "this exists and is currently broken" is worth
    /// knowing, and it is often exactly what the question is about.
    private static string Describe(VeinCompilerService svc, PackagedFile file)
    {
        string name = Path.GetFileName(file.Path);

        CompilationResult result;
        try { result = svc.Compile(new CompileRequest(name, file.Content)); }
        catch (Exception) { return $"  {file.Path}\n"; }

        if (result.Ast is null || BundleModel.Analyze(result.Ast) is not { } model)
            return $"  {file.Path}\n";

        var parts = new List<string>();
        Add(parts, "$", model.ByKind(PrimitiveKind.Shape));
        Add(parts, "#", model.ByKind(PrimitiveKind.Mark));
        Add(parts, "@", model.ByKind(PrimitiveKind.Event));
        Add(parts, "&", model.ByKind(PrimitiveKind.Builder));
        Add(parts, "", model.ByKind(PrimitiveKind.Shard));
        Add(parts, "", model.ByKind(PrimitiveKind.ShardView));
        Add(parts, "", model.ByKind(PrimitiveKind.Publicator));

        string bundle = model.Name.Length > 0 ? $" [bundle {model.Name}]" : "";
        return parts.Count == 0
            ? $"  {file.Path}{bundle}\n"
            : $"  {file.Path}{bundle}: {string.Join(", ", parts)}\n";
    }

    private static void Add(List<string> into, string sigil, IEnumerable<PrimitiveInfo> items)
    {
        foreach (var p in items)
            if (p.Name.Length > 0) into.Add(sigil + p.Name);
    }

    // ---- the file being asked about ----------------------------------------------------------------

    private static (string Text, bool Trimmed) ActiveFile(
        string? path, string? text, string? selection, int budget)
    {
        if (budget <= 0) return ("", false);

        // A selection is the person pointing at something. It wins over the whole file, and it is sent
        // whole even when the file would not fit — you do not select 200 lines by accident.
        bool isSelection = !string.IsNullOrWhiteSpace(selection);
        string body = (isSelection ? selection : text) ?? "";
        if (body.Trim().Length == 0) return ("", false);

        string label = path is null ? "the open buffer" : Path.GetFileName(path);
        string header = isSelection
            ? $"\nThe selected lines in {label}:\n"
            : $"\nThe file currently open, {label}:\n";

        bool trimmed = false;
        if (body.Length > budget) { body = Elide(body, budget); trimmed = true; }

        return (header + body + "\n", trimmed);
    }

    /// Keep the head and the tail, drop the middle, and say so.
    ///
    /// Head and tail rather than the first N characters: a bundle's declarations are at the top and the
    /// shard being asked about is usually further down, so a plain truncation reliably cuts away the
    /// half that prompted the question.
    private static string Elide(string body, int budget)
    {
        const string marker = "\n… (middle of the file omitted) …\n";
        if (budget <= marker.Length + 40) return body[..Math.Min(body.Length, Math.Max(budget, 0))];

        int keep = budget - marker.Length;
        int head = keep * 2 / 3, tail = keep - head;

        return body[..head] + marker + body[^tail..];
    }
}
