using System.Text;
using Vein.Compiler.Ir;

namespace Vein.Compiler.Backends;

/// The first real backend (docs/BACKEND-CONTRACT.md §2): HIR → C# source, compiled by the ordinary
/// `dotnet` toolchain and run against the SECS adapter in Vein.Runtime.SECS.
///
/// Why source rather than IL: the output is readable and debuggable, it reuses the whole .NET toolchain
/// instead of a Reflection.Emit maintenance burden, and it interops directly with ShardECS's own C#
/// components.
///
/// **Scope, stated plainly.** This emits the IDENTITY half of the language — shapes, marks, entities,
/// `target` queries, the fold rule, and the `run once`/`each tick`/`settled` phases. That is the half
/// where compiling is worth ~100×, because it is the half that runs per-entity per-frame. The reactive
/// half (`emit`/`hear` across shards, `@Response`, console, network) stays on the interpreter, where the
/// work is I/O-bound and interpretation costs nothing measurable. `@Print` is the one event bridged
/// here, because a program that cannot say anything cannot be checked against the interpreter.
///
/// Anything outside that subset produces a NOTE rather than silently wrong code — Degrade Explicitly,
/// rule 4 of the contract.
public sealed class CSharpBackend : IVeinBackend
{
    public string Name => "csharp";
    public string OutputExtension => ".g.cs";

    private readonly List<string> _notes = new();
    private readonly HashSet<string> _components = new(StringComparer.Ordinal);

    /// The component the innermost `target` bound, so `self.Health.hp` knows which local to read.
    private string? _selfComponent;

    public BackendResult Emit(IrModule module)
    {
        _notes.Clear();
        _components.Clear();
        foreach (var t in module.Types)
            if (t.Kind == IrTypeKind.Component) _components.Add(t.Name);

        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated />");
        sb.AppendLine("// Emitted by the VeinScript C# backend (docs/BACKEND-CONTRACT.md §2).");
        sb.AppendLine("// Do not edit: regenerate with `veinc build <file> --backend csharp`.");
        sb.AppendLine("using System;");
        sb.AppendLine("using System.Collections.Generic;");
        sb.AppendLine("using Vein.Runtime.SECS;");
        sb.AppendLine();
        sb.AppendLine($"namespace Vein.Generated.{Ident(module.Name)};");
        sb.AppendLine();

        foreach (var t in module.Types) EmitType(sb, t);
        foreach (var s in module.Shards) EmitShard(sb, s);

        EmitEntryPoint(sb, module);

        return new BackendResult(true, new[] { new EmittedFile(Ident(module.Name) + ".g.cs", sb.ToString()) }, _notes);
    }

    // ---- types -----------------------------------------------------------

    private void EmitType(StringBuilder sb, IrType t)
    {
        switch (t.Kind)
        {
            case IrTypeKind.Component: EmitComponent(sb, t); break;

            // A mark is an identity, not data. The adapter keeps marks as named sets rather than empty
            // component types, so a Tag needs no emitted declaration — only the name, which the call
            // sites already carry.
            case IrTypeKind.Tag: break;

            case IrTypeKind.Enum:
                sb.AppendLine($"public enum {Ident(t.Name)} {{ {string.Join(", ", t.Cases.Select(c => Ident(c.Name)))} }}");
                sb.AppendLine();
                break;

            case IrTypeKind.Struct:
                sb.AppendLine($"public sealed class {Ident(t.Name)}");
                sb.AppendLine("{");
                foreach (var f in t.Fields) sb.AppendLine($"    public {Cs(f.Type)} {Ident(f.Name)};");
                sb.AppendLine("}");
                sb.AppendLine();
                break;

            case IrTypeKind.Message:
                // Events are the reactive half; they stay on the interpreter for now.
                _notes.Add($"event @{t.Name} not emitted — the C# backend covers the identity half only; " +
                           "emit/hear stays on the interpreter (Ir/Interp.cs).");
                break;
        }
    }

    /// A component is a STRUCT. An activation needs a snapshot and a working value; as a class each is a
    /// heap allocation, so a frame allocated 2 × entities × systems objects and the GC dominated. As a
    /// struct they are stack copies, and `Fold` being static abstract means contributions never box.
    private void EmitComponent(StringBuilder sb, IrType t)
    {
        string name = Ident(t.Name);
        sb.AppendLine($"public struct {name} : IVeinComponent<{name}>");
        sb.AppendLine("{");
        foreach (var f in t.Fields) sb.AppendLine($"    public {Cs(f.Type)} {Ident(f.Name)};");
        sb.AppendLine();

        // The fold rule, generated per shape because which fields are `folds sum` is a fact about the
        // declaration. A Sum field accumulates each contribution's DELTA from its own snapshot — the
        // distinction that makes `hp -= 1` from two shards mean `hp − 2` and not `2·hp − 2`.
        sb.AppendLine($"    public static {name} Fold({name} committed, List<({name} Snapshot, {name} Current)> contributions)");
        sb.AppendLine("    {");
        sb.AppendLine("        for (int i = 0; i < contributions.Count; i++)");
        sb.AppendLine("        {");
        sb.AppendLine("            var snap = contributions[i].Snapshot;");
        sb.AppendLine("            var cur  = contributions[i].Current;");
        foreach (var f in t.Fields)
        {
            string fn = Ident(f.Name);
            sb.AppendLine("            " + (f.Fold switch
            {
                FoldReducer.Sum => $"committed.{fn} += cur.{fn} - snap.{fn};",
                FoldReducer.Min => $"if (cur.{fn} < committed.{fn}) committed.{fn} = cur.{fn};",
                FoldReducer.Max => $"if (cur.{fn} > committed.{fn}) committed.{fn} = cur.{fn};",
                FoldReducer.First => $"if (i == 0) committed.{fn} = cur.{fn};",
                // Replace, All, Any and no-fold all take the last writer's absolute value, which is what
                // a single-writer field means anyway.
                _ => $"committed.{fn} = cur.{fn};"
            }));
        }
        sb.AppendLine("        }");
        sb.AppendLine("        return committed;");
        sb.AppendLine("    }");
        sb.AppendLine("}");
        sb.AppendLine();
    }

    // ---- shards ----------------------------------------------------------

    private void EmitShard(StringBuilder sb, IrShard shard)
    {
        sb.AppendLine($"public sealed class {Ident(shard.Name)} : VeinSystem");
        sb.AppendLine("{");
        foreach (var f in shard.State) sb.AppendLine($"    public {Cs(f.Type)} {Ident(f.Name)};");
        if (shard.State.Count > 0) sb.AppendLine();

        foreach (var m in shard.Methods)
        {
            string? when = m.Attrs.FirstOrDefault(a => a.Name == "schedule")?.Args.FirstOrDefault()?.ToString();
            string? phase = when switch
            {
                "once" => "Once",
                "tick" or "frame" => "Tick",
                "settled" => "Settled",
                _ => null
            };
            if (phase is null)
            {
                // `every N` is wall-clock and `hear` is the reactive half — both belong to the
                // interpreter, and emitting a stub that never fires would be silently wrong code.
                _notes.Add($"{shard.Name}.{m.Name}: '{when ?? "hear"}' not emitted — " +
                           "the C# backend covers run once / each tick / settled.");
                continue;
            }

            sb.AppendLine($"    public override void {phase}()");
            EmitBlock(sb, m.Body, 1);
        }

        sb.AppendLine("}");
        sb.AppendLine();
    }

    // ---- statements ------------------------------------------------------

    private void EmitBlock(StringBuilder sb, IrBlock block, int depth)
    {
        string pad = new string(' ', depth * 4);
        sb.AppendLine(pad + "{");
        foreach (var s in block.Statements) EmitStmt(sb, s, depth + 1);
        sb.AppendLine(pad + "}");
    }

    private void EmitStmt(StringBuilder sb, IrStmt stmt, int depth)
    {
        string pad = new string(' ', depth * 4);
        switch (stmt)
        {
            case IrBlock b: EmitBlock(sb, b, depth); break;

            case IrLet l:
                sb.AppendLine($"{pad}var {Ident(l.Name)} = {Expr(l.Init)};");
                break;

            case IrAssign a:
                sb.AppendLine($"{pad}{Expr(a.Target)} = {Expr(a.Value)};");
                break;

            case IrIf i:
                sb.AppendLine($"{pad}if ({Expr(i.Cond)})");
                EmitBlock(sb, i.Then, depth);
                if (i.Else is { } e) { sb.AppendLine($"{pad}else"); EmitBlock(sb, e, depth); }
                break;

            case IrLoop { Kind: IrLoopKind.Repeat } r:
                sb.AppendLine($"{pad}for (long __i = 0; __i < {Expr(r.Count)}; __i++)");
                EmitBlock(sb, r.Body, depth);
                break;

            case IrLoop { Kind: IrLoopKind.While } w:
                sb.AppendLine($"{pad}while ({Expr(w.Cond)})");
                EmitBlock(sb, w.Body, depth);
                break;

            case IrLoop { Kind: IrLoopKind.Target } t: EmitTarget(sb, t, depth); break;

            case IrExprStmt es:
                {
                    string text = Expr(es.Expr);
                    if (text.Length > 0) sb.AppendLine($"{pad}{text};");
                    break;
                }

            case IrReturn r2:
                sb.AppendLine(pad + (r2.Value is null ? "return;" : $"return {Expr(r2.Value)};"));
                break;

            case IrBreak: sb.AppendLine($"{pad}break;"); break;
            case IrContinue: sb.AppendLine($"{pad}continue;"); break;

            default:
                _notes.Add($"statement {stmt.GetType().Name} not emitted.");
                sb.AppendLine($"{pad}// [unsupported: {stmt.GetType().Name}]");
                break;
        }
    }

    /// `target $Shape #Mark as self { … }` — one activation per matching entity.
    ///
    /// The activation works on a COPY, and hands the copy plus its snapshot back at the end. That is what
    /// makes a frame order-independent: reads inside the body see the body's own pending writes, every
    /// other unit still sees the committed value, and the fold reconciles them afterwards.
    private void EmitTarget(StringBuilder sb, IrLoop loop, int depth)
    {
        string pad = new string(' ', depth * 4);

        if (loop.Query is not { } q || q.Components.Count == 0)
        {
            // `target <collection> as x` is a plain iteration, not an entity query.
            if (loop.Source is not null)
            {
                sb.AppendLine($"{pad}foreach (var {Ident(loop.Var ?? "__x")} in {Expr(loop.Source)})");
                EmitBlock(sb, loop.Body, depth);
                return;
            }
            _notes.Add("target with no query and no source not emitted.");
            return;
        }

        string comp = Ident(q.Components[0]);
        if (q.Components.Count > 1)
            _notes.Add($"target on {q.Components.Count} components emits the first ({comp}) and filters the rest at runtime — " +
                       "multi-component queries are a follow-on.");

        string marks = string.Join(", ", q.Tags.Select(t => "\"" + t + "\""));
        string prev = _selfComponent!;
        _selfComponent = comp;

        // Two struct copies, both free. `Get` returns by value, and assigning it again gives the working
        // copy — so an activation reads its own pending writes while every other unit still sees the
        // committed value, with no allocation anywhere in the loop.
        sb.AppendLine($"{pad}foreach (var __e in World.Query<{comp}>({marks}))");
        sb.AppendLine(pad + "{");
        sb.AppendLine($"{pad}    var __snap = World.Get<{comp}>(__e);");
        sb.AppendLine($"{pad}    var self_{comp} = __snap;");
        foreach (var s in loop.Body.Statements) EmitStmt(sb, s, depth + 1);
        sb.AppendLine($"{pad}    World.Contribute(__e, __snap, self_{comp});");
        sb.AppendLine(pad + "}");

        _selfComponent = prev;
    }

    // ---- expressions -----------------------------------------------------

    private string Expr(IrExpr? e) => e switch
    {
        null => "",
        IrLiteral l => Literal(l),
        IrLocalRef r => Ident(r.Name),
        IrEntityRef => "__e",
        IrSelfRef => "__e",
        IrTypeNameExpr t => "\"" + t.Name + "\"",
        IrFieldAccess f => FieldAccess(f),
        IrBinary b => $"({Expr(b.Left)} {Op(b.Op)} {Expr(b.Right)})",
        IrUnary u => u.Op == IrUnOp.Neg ? $"(-{Expr(u.Operand)})" : $"(!{Expr(u.Operand)})",
        IrRuntimeCall rc => RuntimeCall(rc),
        IrStructInit si => StructInit(si),
        // A prebuilt like `spawn()` lowers to an ordinary call on a bare name, not to an IrRuntimeCall —
        // only the desugared statements (Emit/AddTag/…) take that path. Route it by name, or it emits as
        // a call to a C# method that does not exist.
        IrCall { Callee: IrLocalRef p } c when IsPrebuilt(p.Name) => RuntimeCall(new IrRuntimeCall(p.Name, c.Args)),
        IrCall c => $"{Expr(c.Callee)}({string.Join(", ", c.Args.Select(Expr))})",
        IrList l => $"new object[] {{ {string.Join(", ", l.Items.Select(Expr))} }}",
        _ => Unsupported(e)
    };

    private string Unsupported(IrExpr e)
    {
        _notes.Add($"expression {e.GetType().Name} not emitted.");
        return $"default /* {e.GetType().Name} */";
    }

    /// `self.Health.hp` arrives as FieldAccess(FieldAccess(Self, "Health"), "hp"). The component hop is
    /// the local the activation is working on, so it collapses to `self_Health.hp`.
    private string FieldAccess(IrFieldAccess f)
    {
        if (f.Receiver is IrSelfRef && _components.Contains(f.Field)) return "self_" + Ident(f.Field);
        if (f.Receiver is IrFieldAccess inner && inner.Receiver is IrSelfRef && _components.Contains(inner.Field))
            return $"self_{Ident(inner.Field)}.{Ident(f.Field)}";
        // A bare `self.hp` inside a target — the component is whatever the query bound.
        if (f.Receiver is IrSelfRef && _selfComponent is { } sc) return $"self_{sc}.{Ident(f.Field)}";
        return $"{Expr(f.Receiver)}.{Ident(f.Field)}";
    }

    /// Names the interpreter answers as prebuilts rather than user functions (Interp's prebuilt switch).
    private static bool IsPrebuilt(string name) => name is "spawn" or "random";

    private string RuntimeCall(IrRuntimeCall c)
    {
        switch (c.Name)
        {
            case "spawn": return "World.Spawn()";

            case "AddComponent":
                return $"World.Attach({Expr(c.Args[0])}, {Expr(c.Args[1])})";

            case "RemoveComponent":
                _notes.Add("`attach … from` (component removal) not emitted yet.");
                return "";

            // Structural changes are DEFERRED to the commit point, after the folds — so no unit in the
            // phase can observe a half-changed world. Same rule the interpreter applies.
            case "AddTag":
                return $"World.Defer(() => World.Mark({Expr(c.Args[0])}, {Expr(c.Args[1])}))";
            case "RemoveTag":
                return $"World.Defer(() => World.Unmark({Expr(c.Args[0])}, {Expr(c.Args[1])}))";

            case "DestroyEntity":
                return $"World.Destroy({Expr(c.Args[0])})";

            case "Emit":
                // @Print is the one bridged event: a program that cannot speak cannot be diffed against
                // the interpreter. Every other event belongs to the reactive half.
                if (c.Args.Count > 0 && c.Args[0] is IrStructInit { TypeName: "Print" } p)
                {
                    var text = p.Fields.FirstOrDefault(f => f.Field == "text").Value;
                    return $"World.Print({Str(text)})";
                }
                _notes.Add($"emit @{(c.Args.FirstOrDefault() as IrStructInit)?.TypeName ?? "?"} not emitted — " +
                           "the reactive half stays on the interpreter.");
                return "";

            case "random": return "0.0 /* seeded random is a follow-on */";

            default:
                _notes.Add($"runtime call {c.Name} not emitted.");
                return "";
        }
    }

    /// Force string context, so `"enemy " + Entity` concatenates rather than failing to compile when the
    /// left operand is not already a string.
    private string Str(IrExpr? e) => e is null ? "\"\"" : $"System.Convert.ToString({Expr(e)})";

    private string StructInit(IrStructInit si)
    {
        if (!_components.Contains(si.TypeName))
        {
            _notes.Add($"struct literal {si.TypeName} not emitted.");
            return "null";
        }
        var sets = si.Fields.Select(f => $"{Ident(f.Field)} = {Expr(f.Value)}");
        return $"new {Ident(si.TypeName)} {{ {string.Join(", ", sets)} }}";
    }

    private static string Literal(IrLiteral l) => l.Kind switch
    {
        IrLiteralKind.String => "\"" + (l.Value?.ToString() ?? "").Replace("\\", "\\\\").Replace("\"", "\\\"") + "\"",
        IrLiteralKind.Bool => (l.Value is true) ? "true" : "false",
        IrLiteralKind.Int => l.Value?.ToString() ?? "0",
        IrLiteralKind.Float or IrLiteralKind.Percent =>
            Convert.ToDouble(l.Value ?? 0).ToString(System.Globalization.CultureInfo.InvariantCulture),
        _ => "default"
    };

    private static string Op(IrBinOp op) => op switch
    {
        IrBinOp.Or => "||", IrBinOp.And => "&&",
        IrBinOp.Eq => "==", IrBinOp.Ne => "!=",
        IrBinOp.Lt => "<", IrBinOp.Gt => ">", IrBinOp.Le => "<=", IrBinOp.Ge => ">=",
        IrBinOp.Add => "+", IrBinOp.Sub => "-", IrBinOp.Mul => "*", IrBinOp.Div => "/",
        _ => "%"
    };

    /// VeinScript `int` is a 64-bit integer (the interpreter carries `long`), so it must not narrow here
    /// — a silently 32-bit backend would disagree with the interpreter only on large values.
    private static string Cs(IrTypeRef t) => t.Name switch
    {
        "int" => "long",
        "float" => "double",
        "bool" => "bool",
        "string" or "Mark" => "string",
        "Entity" => "int",
        "void" => "void",
        _ => Ident(t.Name)
    };

    private static string Ident(string name) => name.Replace('.', '_');

    // ---- entry point -----------------------------------------------------

    private void EmitEntryPoint(StringBuilder sb, IrModule module)
    {
        sb.AppendLine("public static class Program");
        sb.AppendLine("{");
        sb.AppendLine("    /// `--ticks N` matches the interpreter's flag, so the two can be diffed frame for frame.");
        sb.AppendLine("    public static void Main(string[] args)");
        sb.AppendLine("    {");
        sb.AppendLine("        int ticks = 0;");
        sb.AppendLine("        for (int i = 0; i < args.Length; i++)");
        sb.AppendLine("            if (args[i] == \"--ticks\" && i + 1 < args.Length) int.TryParse(args[++i], out ticks);");
        sb.AppendLine("            else if (args[i].StartsWith(\"--ticks=\")) int.TryParse(args[i].Substring(8), out ticks);");
        sb.AppendLine();
        sb.AppendLine("        var world = new VeinWorld();");
        foreach (var s in module.Shards)
            sb.AppendLine($"        world.Register(new {Ident(s.Name)}());");
        sb.AppendLine("        world.Start();");
        sb.AppendLine("        world.Run(ticks);");
        sb.AppendLine("    }");
        sb.AppendLine("}");
    }
}
