using System.Text;
using Vein.Compiler.Ir;

namespace Vein.Compiler.Backends;

/// The first real backend (docs/BACKEND-CONTRACT.md §2): HIR → C# source, compiled by the ordinary
/// `dotnet` toolchain and run against the SECS adapter in Vein.Runtime.SECS.
///
/// Why source rather than IL: the output is readable and debuggable, it reuses the whole .NET toolchain
/// instead of a Reflection.Emit maintenance burden, and it interops directly with ShardECS's own C#
/// components.
///
/// **Scope, stated plainly.** This emits the IDENTITY half of the language — shapes, marks, entities,
/// `target` queries, the fold rule, and the `run once`/`each tick`/`settled` phases. That is the half
/// where compiling is worth ~100×, because it is the half that runs per-entity per-frame. The reactive
/// half (`emit`/`hear` across shards, `@Response`, console, network) stays on the interpreter, where the
/// work is I/O-bound and interpretation costs nothing measurable. `@Print` is the one event bridged
/// here, because a program that cannot say anything cannot be checked against the interpreter.
///
/// Anything outside that subset produces a NOTE rather than silently wrong code — Degrade Explicitly,
/// rule 4 of the contract.
public sealed class CSharpBackend : IVeinBackend
{
    public string Name => "csharp";
    public string OutputExtension => ".g.cs";

    private readonly List<string> _notes = new();
    private readonly HashSet<string> _components = new(StringComparer.Ordinal);

    /// Component declarations by name, so an `attach` with no initialiser can tell whether the shape
    /// declares field defaults — `default(T)` is only the right seed when it does not.
    private readonly Dictionary<string, IrType> _componentTypes = new(StringComparer.Ordinal);

    /// The component the innermost `target` bound, so `self.Health.hp` knows which local to read.
    private string? _selfComponent;

    /// The C# name `Index` resolves to in the loop being emitted. Tracked and restored like
    /// `_selfComponent`, and made unique per depth: C# forbids a nested local shadowing an outer one
    /// (CS0136), so a fixed name would refuse to compile the moment two loops nested.
    private string _indexVar = "0";
    private int _loopDepth;

    public BackendResult Emit(IrModule module)
    {
        _notes.Clear();
        _components.Clear();
        _componentTypes.Clear();
        foreach (var t in module.Types)
            if (t.Kind == IrTypeKind.Component) { _components.Add(t.Name); _componentTypes[t.Name] = t; }

        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated />");
        sb.AppendLine("// Emitted by the VeinScript C# backend (docs/BACKEND-CONTRACT.md §2).");
        sb.AppendLine("// Do not edit: regenerate with `veinc build <file> --backend csharp`.");
        sb.AppendLine("using System;");
        sb.AppendLine("using System.Collections.Generic;");
        sb.AppendLine("using ShardECS.SECS.Systems;");   // IIdentityTag — marks are identity tags
        sb.AppendLine("using Vein.Runtime.SECS;");
        sb.AppendLine();
        sb.AppendLine($"namespace Vein.Generated.{Ident(module.Name)};");
        sb.AppendLine();

        foreach (var t in module.Types) EmitType(sb, t);
        EmitMarks(sb, module);
        foreach (var s in module.Shards) EmitShard(sb, s);

        EmitEntryPoint(sb, module);

        return new BackendResult(true, new[] { new EmittedFile(Ident(module.Name) + ".g.cs", sb.ToString()) }, _notes);
    }

    // ---- types -----------------------------------------------------------

    private void EmitType(StringBuilder sb, IrType t)
    {
        switch (t.Kind)
        {
            case IrTypeKind.Component: EmitComponent(sb, t); break;

            // Marks are emitted together, in a nested `Marks` class — see EmitMarks.
            case IrTypeKind.Tag: break;

            case IrTypeKind.Enum:
                sb.AppendLine($"public enum {Ident(t.Name)} {{ {string.Join(", ", t.Cases.Select(c => Ident(c.Name)))} }}");
                sb.AppendLine();
                break;

            case IrTypeKind.Struct:
                sb.AppendLine($"public sealed class {Ident(t.Name)}");
                sb.AppendLine("{");
                foreach (var f in t.Fields) sb.AppendLine($"    public {Cs(f.Type)} {Ident(f.Name)};");
                sb.AppendLine("}");
                sb.AppendLine();
                break;

            case IrTypeKind.Message:
                // Events are the reactive half; they stay on the interpreter for now.
                _notes.Add($"event @{t.Name} not emitted — the C# backend covers the identity half only; " +
                           "emit/hear stays on the interpreter (Ir/Interp.cs).");
                break;
        }
    }

    /// Every `#Mark` in the module, as SECS identity tags — `IIdentityTag : IComponent`, so a tag is a
    /// zero-data component and an identity carries as many as it likes.
    ///
    /// NESTED in a `Marks` class, and that is the point of the nesting: `$Enemy` and `#Enemy` are
    /// different things in VeinScript, told apart by keyword and sigil, and both are legal in one program.
    /// C# has no sigils, so both would want the identifier `Enemy`. A nested type cannot collide with a
    /// top-level one, so `Marks.Enemy` beside `Enemy` needs no mangling and still reads like the source.
    ///
    /// `readonly struct`, not the `record` SECS's own docs suggest: a tag is a component, and this backend
    /// makes components structs because class components cost 2 × entities × systems allocations a frame.
    /// A zero-field struct allocates nothing, and satisfies the `new()` that `AddIdentity<T>` requires.
    private void EmitMarks(StringBuilder sb, IrModule module)
    {
        var marks = module.Types.Where(t => t.Kind == IrTypeKind.Tag).ToList();
        if (marks.Count == 0) return;

        sb.AppendLine("/// The module's `#Mark`s. Reachable from engine-side C# as");
        sb.AppendLine("/// `secs.GetEntitiesByIdentity<Marks.Name>()`, which a string-keyed mark was not.");
        sb.AppendLine("public static class Marks");
        sb.AppendLine("{");
        foreach (var m in marks)
            sb.AppendLine($"    public readonly struct {Ident(m.Name)} : IIdentityTag {{ }}");
        sb.AppendLine("}");
        sb.AppendLine();
    }

    /// A component is a STRUCT. An activation needs a snapshot and a working value; as a class each is a
    /// heap allocation, so a frame allocated 2 × entities × systems objects and the GC dominated. As a
    /// struct they are stack copies, and `Fold` being static abstract means contributions never box.
    private void EmitComponent(StringBuilder sb, IrType t)
    {
        string name = Ident(t.Name);
        sb.AppendLine($"public struct {name} : IVeinComponent<{name}>");
        sb.AppendLine("{");
        foreach (var f in t.Fields) sb.AppendLine($"    public {Cs(f.Type)} {Ident(f.Name)};");
        sb.AppendLine();

        // The fold rule, generated per shape because which fields are `folds sum` is a fact about the
        // declaration. A Sum field accumulates each contribution's DELTA from its own snapshot — the
        // distinction that makes `hp -= 1` from two shards mean `hp − 2` and not `2·hp − 2`.
        sb.AppendLine($"    public static {name} Fold({name} committed, List<({name} Snapshot, {name} Current)> contributions)");
        sb.AppendLine("    {");
        sb.AppendLine("        for (int i = 0; i < contributions.Count; i++)");
        sb.AppendLine("        {");
        sb.AppendLine("            var snap = contributions[i].Snapshot;");
        sb.AppendLine("            var cur  = contributions[i].Current;");
        foreach (var f in t.Fields)
        {
            string fn = Ident(f.Name);
            sb.AppendLine("            " + (f.Fold switch
            {
                FoldReducer.Sum => $"committed.{fn} += cur.{fn} - snap.{fn};",
                FoldReducer.Min => $"if (cur.{fn} < committed.{fn}) committed.{fn} = cur.{fn};",
                FoldReducer.Max => $"if (cur.{fn} > committed.{fn}) committed.{fn} = cur.{fn};",
                FoldReducer.First => $"if (i == 0) committed.{fn} = cur.{fn};",
                // Replace, All, Any and no-fold all take the last writer's absolute value, which is what
                // a single-writer field means anyway.
                _ => $"committed.{fn} = cur.{fn};"
            }));
        }
        sb.AppendLine("        }");
        sb.AppendLine("        return committed;");
        sb.AppendLine("    }");
        sb.AppendLine("}");
        sb.AppendLine();
    }

    // ---- shards ----------------------------------------------------------

    private void EmitShard(StringBuilder sb, IrShard shard)
    {
        sb.AppendLine($"public sealed class {Ident(shard.Name)} : VeinSystem");
        sb.AppendLine("{");
        foreach (var f in shard.State) sb.AppendLine($"    public {Cs(f.Type)} {Ident(f.Name)};");
        if (shard.State.Count > 0) sb.AppendLine();

        foreach (var m in shard.Methods)
        {
            string? when = m.Attrs.FirstOrDefault(a => a.Name == "schedule")?.Args.FirstOrDefault()?.ToString();
            string? phase = when switch
            {
                "once" => "Once",
                "tick" or "frame" => "Tick",
                "settled" => "Settled",
                _ => null
            };
            if (phase is null)
            {
                // `every N` is wall-clock and `hear` is the reactive half — both belong to the
                // interpreter, and emitting a stub that never fires would be silently wrong code.
                _notes.Add($"{shard.Name}.{m.Name}: '{when ?? "hear"}' not emitted — " +
                           "the C# backend covers run once / each tick / settled.");
                continue;
            }

            sb.AppendLine($"    public override void {phase}()");
            EmitBlock(sb, m.Body, 1);
        }

        sb.AppendLine("}");
        sb.AppendLine();
    }

    // ---- statements ------------------------------------------------------

    private void EmitBlock(StringBuilder sb, IrBlock block, int depth)
    {
        // A transparent block introduces no scope — `bring … as x` declares `x` for the statements that
        // FOLLOW it. Bracing here would make the emitted C# disagree with the interpreter, where an
        // IrBlock has always shared its parent's locals.
        if (block.Transparent)
        {
            foreach (var s in block.Statements) EmitStmt(sb, s, depth);
            return;
        }
        string pad = new string(' ', depth * 4);
        sb.AppendLine(pad + "{");
        foreach (var s in block.Statements) EmitStmt(sb, s, depth + 1);
        sb.AppendLine(pad + "}");
    }

    private void EmitStmt(StringBuilder sb, IrStmt stmt, int depth)
    {
        string pad = new string(' ', depth * 4);
        switch (stmt)
        {
            case IrBlock b: EmitBlock(sb, b, depth); break;

            case IrLet l:
                sb.AppendLine($"{pad}var {Ident(l.Name)} = {Expr(l.Init)};");
                break;

            case IrAssign a:
                sb.AppendLine($"{pad}{Expr(a.Target)} = {Expr(a.Value)};");
                break;

            case IrIf i:
                sb.AppendLine($"{pad}if ({Expr(i.Cond)})");
                EmitBlock(sb, i.Then, depth);
                if (i.Else is { } e) { sb.AppendLine($"{pad}else"); EmitBlock(sb, e, depth); }
                break;

            case IrLoop { Kind: IrLoopKind.Repeat } r:
            {
                // `repeat n as i` binds `i`; `Index` names the same counter, so both spellings work and
                // agree. Unique per depth for the same CS0136 reason as the query loop.
                string prevR = _indexVar;
                _indexVar = "__i" + _loopDepth++;
                sb.AppendLine($"{pad}for (long {_indexVar} = 0; {_indexVar} < {Expr(r.Count)}; {_indexVar}++)");
                sb.AppendLine(pad + "{");
                if (r.Var is not null) sb.AppendLine($"{pad}    var {Ident(r.Var)} = {_indexVar};");
                foreach (var s in r.Body.Statements) EmitStmt(sb, s, depth + 1);
                sb.AppendLine(pad + "}");
                _indexVar = prevR;
                break;
            }
                break;

            case IrLoop { Kind: IrLoopKind.While } w:
                sb.AppendLine($"{pad}while ({Expr(w.Cond)})");
                EmitBlock(sb, w.Body, depth);
                break;

            case IrLoop { Kind: IrLoopKind.Target } t: EmitTarget(sb, t, depth); break;

            case IrExprStmt es:
                {
                    string text = Expr(es.Expr);
                    if (text.Length > 0) sb.AppendLine($"{pad}{text};");
                    break;
                }

            case IrReturn r2:
                sb.AppendLine(pad + (r2.Value is null ? "return;" : $"return {Expr(r2.Value)};"));
                break;

            case IrBreak: sb.AppendLine($"{pad}break;"); break;
            case IrContinue: sb.AppendLine($"{pad}continue;"); break;

            default:
                _notes.Add($"statement {stmt.GetType().Name} not emitted.");
                sb.AppendLine($"{pad}// [unsupported: {stmt.GetType().Name}]");
                break;
        }
    }

    /// `target $Shape #Mark as self { … }` — one activation per matching entity.
    ///
    /// The activation works on a COPY, and hands the copy plus its snapshot back at the end. That is what
    /// makes a frame order-independent: reads inside the body see the body's own pending writes, every
    /// other unit still sees the committed value, and the fold reconciles them afterwards.
    private void EmitTarget(StringBuilder sb, IrLoop loop, int depth)
    {
        string pad = new string(' ', depth * 4);

        if (loop.Query is not { } q || q.Components.Count == 0)
        {
            // `target <collection> as x` is a plain iteration, not an entity query.
            if (loop.Source is not null)
            {
                // Same counter discipline as the query form, so `Index` means the same thing in both.
                string prevC = _indexVar;
                _indexVar = "__idx" + _loopDepth++;
                sb.AppendLine($"{pad}long {_indexVar} = -1;");
                sb.AppendLine($"{pad}foreach (var {Ident(loop.Var ?? "__x")} in {Expr(loop.Source)})");
                sb.AppendLine(pad + "{");
                sb.AppendLine($"{pad}    {_indexVar}++;");
                foreach (var s in loop.Body.Statements) EmitStmt(sb, s, depth + 1);
                sb.AppendLine(pad + "}");
                _indexVar = prevC;
                return;
                return;
            }
            _notes.Add("target with no query and no source not emitted.");
            return;
        }

        var comps = q.Components.Select(Ident).ToList();
        string comp = comps[0];

        // Marks are TYPE ARGUMENTS now, not strings: `Query<Health, Marks.Enemy>()`. A mistyped mark stops
        // compiling instead of matching nothing, and the filter stays inside the query, so the cache holds
        // the finished list rather than re-testing every tag per entity per frame.
        //
        // VeinWorld carries an overload per mark count, because `ComponentBuckets` is generic-only — there
        // is no `Has(int, Type)` to loop over. Three covers every query in the samples; beyond that the
        // note is honest rather than emitting something that will not compile.
        if (q.Tags.Count > 3)
        {
            _notes.Add($"target on {q.Tags.Count} marks not emitted — VeinWorld.Query has overloads for up " +
                       "to 3. Add another overload, or split the query.");
            return;
        }
        string marks = q.Tags.Count == 0 ? "" : ", " + string.Join(", ", q.Tags.Select(t => "Marks." + Ident(t)));
        string prev = _selfComponent!;
        _selfComponent = comp;

        // Several components are an AND. `World.Query<T>` indexes on ONE, so the first drives the loop and
        // the rest are tested per entity — the entity is skipped unless it carries all of them.
        //
        // Emitting only the first was a real disagreement with the interpreter, not a missing feature: the
        // loop visited entities lacking the others, and the body then referenced a `self_<Other>` that was
        // never declared, so the generated C# did not even compile.
        // The counter is declared OUTSIDE the loop and bumped INSIDE, after the `continue` guards below.
        // Incrementing at the top would count entities this loop skips, and the interpreter never sees
        // them at all — its `Query` filters every component before iterating. Same numbers, or the two
        // runtimes disagree on `Index`.
        string prevIdx = _indexVar;
        _indexVar = "__idx" + _loopDepth++;
        sb.AppendLine($"{pad}long {_indexVar} = -1;");
        sb.AppendLine($"{pad}foreach (var __e in World.Query<{comp}{marks}>())");
        sb.AppendLine(pad + "{");
        foreach (var c in comps.Skip(1))
            sb.AppendLine($"{pad}    if (!World.Has<{c}>(__e)) continue;");
        sb.AppendLine($"{pad}    {_indexVar}++;");

        // Two struct copies per component, both free. `Get` returns by value, and assigning it again gives
        // the working copy — so an activation reads its own pending writes while every other unit still
        // sees the committed value, with no allocation anywhere in the loop.
        foreach (var c in comps)
        {
            sb.AppendLine($"{pad}    var __snap_{c} = World.Get<{c}>(__e);");
            sb.AppendLine($"{pad}    var self_{c} = __snap_{c};");
        }

        foreach (var s in loop.Body.Statements) EmitStmt(sb, s, depth + 1);

        // Every component the query bound is contributed, so a fold on any of them reconciles — writing
        // back only the first would silently drop writes to the others.
        foreach (var c in comps)
            sb.AppendLine($"{pad}    World.Contribute(__e, __snap_{c}, self_{c});");
        sb.AppendLine(pad + "}");

        _selfComponent = prev;
        _indexVar = prevIdx;
    }

    // ---- expressions -----------------------------------------------------

    private string Expr(IrExpr? e) => e switch
    {
        null => "",
        IrLiteral l => Literal(l),
        IrLocalRef r => Ident(r.Name),
        IrEntityRef => "__e",
        IrLoopIndexRef => _indexVar,
        IrSelfRef => "__e",
        IrTypeNameExpr t => "\"" + t.Name + "\"",
        IrFieldAccess f => FieldAccess(f),
        IrBinary b => $"({Expr(b.Left)} {Op(b.Op)} {Expr(b.Right)})",
        IrUnary u => u.Op == IrUnOp.Neg ? $"(-{Expr(u.Operand)})" : $"(!{Expr(u.Operand)})",
        IrRuntimeCall rc => RuntimeCall(rc),
        IrStructInit si => StructInit(si),
        // A prebuilt like `spawn()` lowers to an ordinary call on a bare name, not to an IrRuntimeCall —
        // only the desugared statements (Emit/AddTag/…) take that path. Route it by name, or it emits as
        // a call to a C# method that does not exist.
        IrCall { Callee: IrLocalRef p } c when IsPrebuilt(p.Name) => RuntimeCall(new IrRuntimeCall(p.Name, c.Args)),
        IrCall c => $"{Expr(c.Callee)}({string.Join(", ", c.Args.Select(Expr))})",
        IrList l => $"new object[] {{ {string.Join(", ", l.Items.Select(Expr))} }}",
        _ => Unsupported(e)
    };

    private string Unsupported(IrExpr e)
    {
        _notes.Add($"expression {e.GetType().Name} not emitted.");
        return $"default /* {e.GetType().Name} */";
    }

    /// `self.Health.hp` arrives as FieldAccess(FieldAccess(Self, "Health"), "hp"). The component hop is
    /// the local the activation is working on, so it collapses to `self_Health.hp`.
    private string FieldAccess(IrFieldAccess f)
    {
        if (f.Receiver is IrSelfRef && _components.Contains(f.Field)) return "self_" + Ident(f.Field);
        if (f.Receiver is IrFieldAccess inner && inner.Receiver is IrSelfRef && _components.Contains(inner.Field))
            return $"self_{Ident(inner.Field)}.{Ident(f.Field)}";
        // A bare `self.hp` inside a target — the component is whatever the query bound.
        if (f.Receiver is IrSelfRef && _selfComponent is { } sc) return $"self_{sc}.{Ident(f.Field)}";
        return $"{Expr(f.Receiver)}.{Ident(f.Field)}";
    }

    /// Names the interpreter answers as prebuilts rather than user functions (Interp's prebuilt switch).
    private static bool IsPrebuilt(string name) => name is "spawn" or "random";

    private string RuntimeCall(IrRuntimeCall c)
    {
        switch (c.Name)
        {
            case "spawn": return "World.Spawn()";

            // `attach $C to e { … }` carries a struct init and emits directly. `attach $C to e` with no
            // initialiser carries a bare TYPE NAME instead, which through Expr would emit as a string
            // literal and bind T to string — code that does not compile. The interpreter seeds that case
            // from the shape's declared defaults, so `default(T)` matches it exactly while the shape
            // declares none, and is reported rather than guessed at when it does.
            case "AddComponent":
                if (c.Args.Count > 1 && c.Args[1] is IrTypeNameExpr at)
                {
                    if (_componentTypes.TryGetValue(at.Name, out var decl) && decl.Fields.Any(f => f.Default is not null))
                    {
                        _notes.Add($"attach ${at.Name} with no initialiser not emitted — the shape declares " +
                                   "field defaults, and the emitted struct seeds them as zero.");
                        return "";
                    }
                    return $"World.Attach({Expr(c.Args[0])}, default({Ident(at.Name)}))";
                }
                return $"World.Attach({Expr(c.Args[0])}, {Expr(c.Args[1])})";

            // `unattach $C from e`. The shape arrives as a TYPE NAME, not a value, so it becomes the
            // generic argument — running it through Expr would emit the name as a string literal and
            // bind T to string.
            case "RemoveComponent":
                if (c.Args.Count > 1 && c.Args[1] is IrTypeNameExpr rt)
                    return $"World.Detach<{Ident(rt.Name)}>({Expr(c.Args[0])})";
                _notes.Add("`unattach` with no shape name not emitted.");
                return "";

            // Structural changes are DEFERRED to the commit point, after the folds — so no unit in the
            // phase can observe a half-changed world. Same rule the interpreter applies.
            // The mark arrives as a TYPE NAME, so it becomes the generic argument — `Expr` would emit it
            // as a string literal, which is what these used to be.
            case "AddTag" when c.Args.Count > 1 && c.Args[1] is IrTypeNameExpr addTag:
                return $"World.Defer(() => World.MarkAs<Marks.{Ident(addTag.Name)}>({Expr(c.Args[0])}))";
            case "RemoveTag" when c.Args.Count > 1 && c.Args[1] is IrTypeNameExpr remTag:
                return $"World.Defer(() => World.UnmarkAs<Marks.{Ident(remTag.Name)}>({Expr(c.Args[0])}))";

            case "DestroyEntity":
                return $"World.Destroy({Expr(c.Args[0])})";

            case "Emit":
                // @Print is the one bridged event: a program that cannot speak cannot be diffed against
                // the interpreter. Every other event belongs to the reactive half.
                if (c.Args.Count > 0 && c.Args[0] is IrStructInit { TypeName: "Print" } p)
                {
                    var text = p.Fields.FirstOrDefault(f => f.Field == "text").Value;
                    return $"World.Print({Str(text)})";
                }
                _notes.Add($"emit @{(c.Args.FirstOrDefault() as IrStructInit)?.TypeName ?? "?"} not emitted — " +
                           "the reactive half stays on the interpreter.");
                return "";

            // The same seeded generator the interpreter uses, so `chance` makes identical draws on both
            // sides. Emitting a constant made `chance 30%` mean ALWAYS in compiled code (0.0 < 0.30),
            // which compiled and ran and quietly disagreed — the one failure mode the contract forbids.
            case "random": return "World.Random()";

            default:
                _notes.Add($"runtime call {c.Name} not emitted.");
                return "";
        }
    }

    /// Force string context, so `"enemy " + Entity` concatenates rather than failing to compile when the
    /// left operand is not already a string.
    private string Str(IrExpr? e) => e is null ? "\"\"" : $"System.Convert.ToString({Expr(e)})";

    private string StructInit(IrStructInit si)
    {
        if (!_components.Contains(si.TypeName))
        {
            _notes.Add($"struct literal {si.TypeName} not emitted.");
            return "null";
        }
        var sets = si.Fields.Select(f => $"{Ident(f.Field)} = {Expr(f.Value)}");
        return $"new {Ident(si.TypeName)} {{ {string.Join(", ", sets)} }}";
    }

    private static string Literal(IrLiteral l) => l.Kind switch
    {
        IrLiteralKind.String => "\"" + (l.Value?.ToString() ?? "").Replace("\\", "\\\\").Replace("\"", "\\\"") + "\"",
        IrLiteralKind.Bool => (l.Value is true) ? "true" : "false",
        IrLiteralKind.Int => l.Value?.ToString() ?? "0",
        IrLiteralKind.Float or IrLiteralKind.Percent =>
            Convert.ToDouble(l.Value ?? 0).ToString(System.Globalization.CultureInfo.InvariantCulture),
        _ => "default"
    };

    private static string Op(IrBinOp op) => op switch
    {
        IrBinOp.Or => "||", IrBinOp.And => "&&",
        IrBinOp.Eq => "==", IrBinOp.Ne => "!=",
        IrBinOp.Lt => "<", IrBinOp.Gt => ">", IrBinOp.Le => "<=", IrBinOp.Ge => ">=",
        IrBinOp.Add => "+", IrBinOp.Sub => "-", IrBinOp.Mul => "*", IrBinOp.Div => "/",
        _ => "%"
    };

    /// VeinScript `int` is a 64-bit integer (the interpreter carries `long`), so it must not narrow here
    /// — a silently 32-bit backend would disagree with the interpreter only on large values.
    private static string Cs(IrTypeRef t) => t.Name switch
    {
        "int" => "long",
        "float" => "double",
        "bool" => "bool",
        "string" or "Mark" => "string",
        "Entity" => "int",
        "void" => "void",
        _ => Ident(t.Name)
    };

    /// C# reserved words. A VeinScript name is not constrained by C#'s grammar, so `let out = …` is
    /// ordinary source here and `var out = …` is not valid C# — the `@` prefix is exactly the escape
    /// hatch C# provides for it. Latent until `bring … as out` made user-chosen names easy to reach.
    private static readonly HashSet<string> CsKeywords = new(StringComparer.Ordinal)
    {
        "abstract","as","base","bool","break","byte","case","catch","char","checked","class","const",
        "continue","decimal","default","delegate","do","double","else","enum","event","explicit","extern",
        "false","finally","fixed","float","for","foreach","goto","if","implicit","in","int","interface",
        "internal","is","lock","long","namespace","new","null","object","operator","out","override",
        "params","private","protected","public","readonly","ref","return","sbyte","sealed","short",
        "sizeof","stackalloc","static","string","struct","switch","this","throw","true","try","typeof",
        "uint","ulong","unchecked","unsafe","ushort","using","virtual","void","volatile","while"
    };

    private static string Ident(string name)
    {
        string s = name.Replace('.', '_');
        return CsKeywords.Contains(s) ? "@" + s : s;
    }

    // ---- entry point -----------------------------------------------------

    private void EmitEntryPoint(StringBuilder sb, IrModule module)
    {
        sb.AppendLine("public static class Program");
        sb.AppendLine("{");
        sb.AppendLine("    /// `--ticks N` matches the interpreter's flag, so the two can be diffed frame for frame.");
        sb.AppendLine("    public static void Main(string[] args)");
        sb.AppendLine("    {");
        sb.AppendLine("        int ticks = 0;");
        sb.AppendLine("        for (int i = 0; i < args.Length; i++)");
        sb.AppendLine("            if (args[i] == \"--ticks\" && i + 1 < args.Length) int.TryParse(args[++i], out ticks);");
        sb.AppendLine("            else if (args[i].StartsWith(\"--ticks=\")) int.TryParse(args[i].Substring(8), out ticks);");
        sb.AppendLine();
        sb.AppendLine("        var world = new VeinWorld();");
        foreach (var s in module.Shards)
            sb.AppendLine($"        world.Register(new {Ident(s.Name)}());");
        sb.AppendLine("        world.Start();");
        sb.AppendLine("        world.Run(ticks);");
        sb.AppendLine("    }");
        sb.AppendLine("}");
    }
}
